trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
- name: artifact_dir
  value: oozie_example

steps:
- bash: |
    mkdir -p "$(Build.ArtifactStagingDirectory)/$(artifact_dir)"
    cp -r examples "$(Build.ArtifactStagingDirectory)/$(artifact_dir)/"
  displayName: 'Include Oozie apps code to Build Artifacts'

- task: PublishBuildArtifacts@1
  displayName: Publish Oozie Build Artifacts
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/$(artifact_dir)'
    artifactName: oozie_example
